/*
var questions = [
	{"What nationality was Chopin": "Polish"},
	{"What\'s the best known artificial international language": "esperanto"},
	{"Who lived at 221B, Baker Street, London": "Sherlock Holmes"},
	{"Who cut Van Gogh\'s ear": "he did"},
	{"Where did Salvador Dali live": "Figueras"},
	{"Who painted the Mona Lisa": "Da Vinci"},
	{"What Spanish artist said he would eat his wife when she died": "Dali"},
	{"Who wrote Julius Caesar, Macbeth and Hamlet": "Shakespeare"},
	{"Who wrote Lazarillo de Tormes": "anonymous"},
	{"What did the crocodile swallow in Peter Pan": "alarm clock"},
	{"Where was Lope de Vega born": "Madrid"},
	{"What are the first three words of the bible": "In the beginning"},
	{"What did the 7 dwarves do for a job": "miners"},
	{"Who painted the Sistine Chapel": "Michelangelo"},
	{"Who wrote La Colmena": "Cela"},
	{"Name a famous detective who smoked a pipe and played the violin.": "S. Holmes"},
	{"How many people went onto Noah\'s Ark": "8"},
	{"What was the name of Don Quijote\'s horse": "Rocinante"},
	{"Who was Robin Hood\'s girlfriend": "Maid Marian"},
	{"Who wrote the James Bond books": "Ian Fleming"},
	{"Who wrote Dr. Jekyll and Mr. Hyde": "Robert Louis Stevenson"},
	{"Who said, \"I think, therefore I am\"": "Descartes"},
	{"Who wrote the Ugly Duckling": "Hans Christian Andersen"},
	{"Where was El Greco born": "Greece"},
	{"What\'s the Hungarian word for pepper": "paprika"},
	{"Which painter did the group Mecano write a song about": "Dali"},
	{"Who wrote the Satanic Verses": "Salman Rushdie"},
	{"What was the first theatre play in Spain": "La Celestina"},
	{"What\'s the most important book in the Moslem religion": "Koran"},
	{"When was Elvis\' first ever concert": "1954"},
	{"Who sang \"My Way\"": "Frank Sinatra"},
	{"Who as the main actor in \"Cocktail\"": "Tom Cruise"},
	{"Who was the main actor in Superman 2": "Christopher Reeve"},
	{"Who did Madonna marry": "Sean Penn"},
	{"Who sang, \"I\'m dreaming of a white Christmas\"": "Bing Crosby"},
	{"Name the two main actors in \"The Sting\".": "Paul Newman and Robert Redford"},
	{"What year did Elvis Presley die": "1977"},
	{"What film star who was in 9« weeks is now a boxer": "Mickey Rourke"},
	{"Who were the two main actors in \"Pretty Woman\"": "Julia Roberts and Richard Gere"},
	{"Name two actors who played James Bond.": "Sean Connery, George Lazenby, Timothy Dalton, Pierce Brosnan"},
	{"Who was the director of the film \"Psycho\"": "A¤fred Hitchcock"},
	{"In which city is Hollywood": "Los Angeles"},
	{"Who did John Lennon marry": "Yoko Ono"},
	{"Name three of the beatles": "Ringo Starr, John Lennon, Paul McCartney, George Harrison"},
	{"Which 2 actors were in \"Gone with the wind\"": "Clark Gable and Vivien Leigh"},
	{"Who wrote the song \"Johnny be good\"": "Chuck Berry"},
	{"What was the first film with sound": "the Jazz Singer"},
	{"How many oscars did Alfred Hitchcock win": "none"},
	{"Which film about Germany won most prizes in 1976": "Cabaret"},
	{"What year did the drummer of Def Lepperd loose his arm": "1984"},
	{"Where are the Dolomites": "Italy"},
	{"What\'s the capital of Kenya": "Nairobi"},
	{"Which is the largest ocean": "Pacific"},
	{"What\'s the capital of Honduras": "Tegucigarpa"},
	{"What\'s the capital of Ethiopia": "Addis Ababa"},
	{"What\'s the capital of Ecuador": "Quito"},
	{"What\'s the smallest country in the world": "Vatican City"},
	{"What is the capital of Australia": "Canberra"},
	{"What\'s the largest city in \"India\"": "Bombay"},
	{"How many avenues radiate from the Arc de Triomphe in Paris": "12"},
	{"What\'s the capital of Denmark": "Copenhagen"},
	{"What\'s the capital of Brazil": "Brasilia"},
	{"Which river goes through London": "Thames"},
	{"What\'s the highest mountain in Africa": "Kilimanjaro"},
	{"What\'s the capital of Finland": "Helsinki"},
	{"Where is Mulhacen": "Granada Spain"},
	{"How many states are there in the United States of America": "50"},
	{"Which river passes through Madrid": "Manzanares"},
	{"Which German city is famous for the perfume it produces": "Cologne"},
	{"What\'s the capital of Monaco": "Monaco"},
	{"Which is Britain\'s second largest city": "Birmingham"},
	{"What is 15 metres high, 8 metres wide and 240 kilometers long": "Wall"},
	{"What\'s the highest mountain in the world": "Everest"},
	{"What\'s the capital of Scotland": "Edinburgh"},
	{"Which country has the largest area: Australia, Brazil or \"India\"": "Brazil"},
	{"Where are the Luxembourg Gardens": "Paris"},
	{"Which mountains are between Spain and France": "Pyrenees"},
	{"Which is the smallest ocean": "Artic"},
	{"How many wives did Henry the Eighth have": "six"},
	{"Where was Franco born": "Teruel"},
	{"When did the first man go into space": "},1961"},
	{"Who was the first man in space": "Gagarin"},
	{"Where did the first atomic bomb explode for the first time in Japan": "Hiroshima"},
	{"Who said, \"Vini, vidi, vici\"": "Caesar"},
	{"What year did Christopher Columbus go to America": "1492"},
	{"Who did Lady Diana Spencer marry": "Prince Charles"},
	{"Who did Prince Rainier of Monaco marry": "Grace Kelly"},
	{"What year did the Spanish Civil War end": "1939"},
	{"When did the First World War start": "1914"},
	{"When did the Second World War end": "1945"},
	{"Can Queen Elizabeth the Second vote": "no"},
	{"Who was the first president of America": "Washington"},
	{"Who did Franco designate as his successor in 1969": "Juan Carlos"},
	{"How many fingers did Ann Boleyn have": "11"},
	{"Who was Felipe el Hermoso\'s wife": "Juana la Loca"},
	{"Did Neil Armstrong put his l. or his r. foot on the moon first": "left"},
	{"What year did King Juan Carlos get married": "1962"},
	{"In what decade was the last execution at the Tower of London": "1940\'s"},
	{"When did the Americans leave Vietnam": "1973"},
	{"Who was the first man on the moon": "Armstrong"},
	{"What religion was Adolf Hitler": "Catholic"},
	{"Where was Marco Polo\'s home town": "Venice"},
	{"Which Italian leader was terribly afraid of the evil eye": "Mussolini"},
	{"How many children has Queen Elizabeth the Second got": "4"},
	{"What\'s the real name of Siddartha Gautama": "Buddha"},
	{"What\'s the name of the famous big clock in London": "Big Ben"},
	{"Where was Christopher Columbus born": "Genoa"},
	{"When did the American Civil War end": "1865"},
	{"What country gave Florida to the USA in 1891": "Spain"},
	{"Who gave his name to the month of July": "Julius Caesar"},
	{"What did the Montgolfier brothers invent": "the balloon"},
	{"Who is the president of Iraq": "Sadam Hussein"},
	{"When was President Kennedy killed": "1963"},
	{"What stopped in London at 3.45 on August 5th, 1975": "Big Ben"},
	{"What nationality was Marco Polo": "Italian"},
	{"Who won a gold medal for Spain in cycling in the 1992 Olympics": "Jose Manuel Moreno"},
	{"Who is the tallest basketball player in the world": "Manute Boll - 2.31m"},
	{"What do you use to take a cork out of a bottle": "a corkscrew"},
	{"What language has the most words": "English"},
	{"What\'s the name of the main airport in Madrid": "Barajas"},
	{"What money do they use in Japan": "yen"},
	{"What year did Paquirri die": "1984 or 1985"},
	{"Where does the American president live": "The White House"},
	{"What is the first letter on a typewriter": "Q"},
	{"What do the opposite sides of a dice add up to": "7"},
	{"Which fast food restaurants were established by Ray Kroc": "McDondalds"},
	{"How long is a round in boxing": "3 minutes"},
	{"Who is the Prime Minister of Britain": "John Major"},
	{"What\'s the highest score in a gymnastics exercise": "10"},
	{"What time do the pubs normally close in England": "11 o\'clock"},
	{"How many months have 31 days": "7"},
	{"How many eyes are there on a pack of 52 cards": "42"},
	{"What is the main language in Albania": "Tosco"},
	{"What\'s the fastest passenger plane in the world": "concorde"},
	{"What are the Sun, the \"Independent and the Guardian\"": "newspapers"},
	{"How many coloured balls are there in billiards": "15"},
	{"What\'s the longest word in Spanish": "superextraordinarissimo"},
	{"How many players are there in a basketball team": "5"},
	{"Which is the most spoken language": "Chinese"},
	{"How many lanes does an olympic swimming pool have": "8"},
	{"In what language does \"obrigado\" mean \"thank you\"": "Portuguese"},
	{"How many squares are there on a chess board": "64"},
	{"How many prongs are there on a fork": "4"},
	{"Who starts first in chess": "white"},
	{"How many events are there in the decathlon": "10"},
	{"What activity other than jumping are kangaroos good at": "boxing"},
	{"How many players are there in a volleyball team": "6"},
	{"What are the five colours of the Olympic rings": "r,y,g,blue black"},
	{"Where are the most expensive seats at a bullfight": "in the shade"},
	{"Who named a perfume for her fashion shows on the 5th day of the month": "Chanel"},
	{"How many dots are there on two dice": "42"},
	{"What horoscope sign has a crab": "cancer"},
	{"In which shop can you buy books in England": "bookshop"},
	{"Where does the British Prime Minister live": "10, Downing Street"},
	{"How long is the compulsory military service in England": "it doesn\'t exist"},
	{"What does the female praying mantis do after she\'s made love": "eats the male"},
	{"How many colours are there in a rainbow": "7"},
	{"How many legs has a spider got": "8"},
	{"What are the three primary colours": "red, blue and yellow"},
	{"What type of elephant has got the biggest ears": "African"},
	{"Who invented the electric light bulb": "Thomas Edison"},
	{"Who invented the telephone": "Bell"},
	{"Which nail grows fastest": "middle"},
	{"What temperature does water boil at": "100C"},
	{"Who discovered penicillin": "Fleming"},
	{"What did Joseph Priesley discover in 1774": "Oxygen"},
	{"Where is the smallest bone in the body": "ear"},
	{"Which is the only mammal that can\'t jump": "elephant"},
	{"What does the roman numeral C represent": "100"},
	{"What colour is a panda": "black and white"},
	{"What\'s the smallest type of tree in the world": "Bonsai"},
	{"Who invented television": "John Logie Baird"},
	{"Who said E=mc2": "Einstein"},
	{"Which planet is nearest the sun": "Mercury"},
	{"What colours make purple": "red and blue"},
	{"What\'s the hardest rock": "diamond"},
	{"How much does a litre of water weigh": "1kg"}
];
*/

var questions = [];

(function() {
	var object = {
		"What nationality was Chopin": "Polish",
		"What\'s the best known artificial international language": "esperanto",
		"Who lived at 221B, Baker Street, London": "Sherlock Holmes",
		"Who cut Van Gogh\'s ear": "he did",
		"Where did Salvador Dali live": "Figueras",
		"Who painted the Mona Lisa": "Da Vinci",
		"What Spanish artist said he would eat his wife when she died": "Dali",
		"Who wrote Julius Caesar, Macbeth and Hamlet": "Shakespeare",
		"Who wrote Lazarillo de Tormes": "anonymous",
		"What did the crocodile swallow in Peter Pan": "alarm clock",
		"Where was Lope de Vega born": "Madrid",
		"What are the first three words of the bible": "In the beginning",
		"What did the 7 dwarves do for a job": "miners",
		"Who painted the Sistine Chapel": "Michelangelo",
		"Who wrote La Colmena": "Cela",
		"Name a famous detective who smoked a pipe and played the violin.": "S. Holmes",
		"How many people went onto Noah\'s Ark": "8",
		"What was the name of Don Quijote\'s horse": "Rocinante",
		"Who was Robin Hood\'s girlfriend": "Maid Marian",
		"Who wrote the James Bond books": "Ian Fleming",
		"Who wrote Dr. Jekyll and Mr. Hyde": "Robert Louis Stevenson",
		"Who said, \"I think, therefore I am\"": "Descartes",
		"Who wrote the Ugly Duckling": "Hans Christian Andersen",
		"Where was El Greco born": "Greece",
		"What\'s the Hungarian word for pepper": "paprika",
		"Which painter did the group Mecano write a song about": "Dali",
		"Who wrote the Satanic Verses": "Salman Rushdie",
		"What was the first theatre play in Spain": "La Celestina",
		"What\'s the most important book in the Moslem religion": "Koran",
		"When was Elvis\' first ever concert": "1954",
		"Who sang \"My Way\"": "Frank Sinatra",
		"Who as the main actor in \"Cocktail\"": "Tom Cruise",
		"Who was the main actor in Superman 2": "Christopher Reeve",
		"Who did Madonna marry": "Sean Penn",
		"Who sang, \"I\'m dreaming of a white Christmas\"": "Bing Crosby",
		"Name the two main actors in \"The Sting\".": "Paul Newman and Robert Redford",
		"What year did Elvis Presley die": "1977",
		"What film star who was in 9« weeks is now a boxer": "Mickey Rourke",
		"Who were the two main actors in \"Pretty Woman\"": "Julia Roberts and Richard Gere",
		"Name two actors who played James Bond.": "Sean Connery, George Lazenby, Timothy Dalton, Pierce Brosnan",
		"Who was the director of the film \"Psycho\"": "A¤fred Hitchcock",
		"In which city is Hollywood": "Los Angeles",
		"Who did John Lennon marry": "Yoko Ono",
		"Name three of the beatles": "Ringo Starr, John Lennon, Paul McCartney, George Harrison",
		"Which 2 actors were in \"Gone with the wind\"": "Clark Gable and Vivien Leigh",
		"Who wrote the song \"Johnny be good\"": "Chuck Berry",
		"What was the first film with sound": "the Jazz Singer",
		"How many oscars did Alfred Hitchcock win": "none",
		"Which film about Germany won most prizes in 1976": "Cabaret",
		"What year did the drummer of Def Lepperd loose his arm": "1984",
		"Where are the Dolomites": "Italy",
		"What\'s the capital of Kenya": "Nairobi",
		"Which is the largest ocean": "Pacific",
		"What\'s the capital of Honduras": "Tegucigarpa",
		"What\'s the capital of Ethiopia": "Addis Ababa",
		"What\'s the capital of Ecuador": "Quito",
		"What\'s the smallest country in the world": "Vatican City",
		"What is the capital of Australia": "Canberra",
		"What\'s the largest city in \"India\"": "Bombay",
		"How many avenues radiate from the Arc de Triomphe in Paris": "12",
		"What\'s the capital of Denmark": "Copenhagen",
		"What\'s the capital of Brazil": "Brasilia",
		"Which river goes through London": "Thames",
		"What\'s the highest mountain in Africa": "Kilimanjaro",
		"What\'s the capital of Finland": "Helsinki",
		"Where is Mulhacen": "Granada Spain",
		"How many states are there in the United States of America": "50",
		"Which river passes through Madrid": "Manzanares",
		"Which German city is famous for the perfume it produces": "Cologne",
		"What\'s the capital of Monaco": "Monaco",
		"Which is Britain\'s second largest city": "Birmingham",
		"What is 15 metres high, 8 metres wide and 240 kilometers long": "Wall",
		"What\'s the highest mountain in the world": "Everest",
		"What\'s the capital of Scotland": "Edinburgh",
		"Which country has the largest area: Australia, Brazil or \"India\"": "Brazil",
		"Where are the Luxembourg Gardens": "Paris",
		"Which mountains are between Spain and France": "Pyrenees",
		"Which is the smallest ocean": "Artic",
		"How many wives did Henry the Eighth have": "six",
		"Where was Franco born": "Teruel",
		"When did the first man go into space": ",1961",
		"Who was the first man in space": "Gagarin",
		"Where did the first atomic bomb explode for the first time in Japan": "Hiroshima",
		"Who said, \"Vini, vidi, vici\"": "Caesar",
		"What year did Christopher Columbus go to America": "1492",
		"Who did Lady Diana Spencer marry": "Prince Charles",
		"Who did Prince Rainier of Monaco marry": "Grace Kelly",
		"What year did the Spanish Civil War end": "1939",
		"When did the First World War start": "1914",
		"When did the Second World War end": "1945",
		"Can Queen Elizabeth the Second vote": "no",
		"Who was the first president of America": "Washington",
		"Who did Franco designate as his successor in 1969": "Juan Carlos",
		"How many fingers did Ann Boleyn have": "11",
		"Who was Felipe el Hermoso\'s wife": "Juana la Loca",
		"Did Neil Armstrong put his l. or his r. foot on the moon first": "left",
		"What year did King Juan Carlos get married": "1962",
		"In what decade was the last execution at the Tower of London": "1940\'s",
		"When did the Americans leave Vietnam": "1973",
		"Who was the first man on the moon": "Armstrong",
		"What religion was Adolf Hitler": "Catholic",
		"Where was Marco Polo\'s home town": "Venice",
		"Which Italian leader was terribly afraid of the evil eye": "Mussolini",
		"How many children has Queen Elizabeth the Second got": "4",
		"What\'s the real name of Siddartha Gautama": "Buddha",
		"What\'s the name of the famous big clock in London": "Big Ben",
		"Where was Christopher Columbus born": "Genoa",
		"When did the American Civil War end": "1865",
		"What country gave Florida to the USA in 1891": "Spain",
		"Who gave his name to the month of July": "Julius Caesar",
		"What did the Montgolfier brothers invent": "the balloon",
		"Who is the president of Iraq": "Sadam Hussein",
		"When was President Kennedy killed": "1963",
		"What stopped in London at 3.45 on August 5th, 1975": "Big Ben",
		"What nationality was Marco Polo": "Italian",
		"Who won a gold medal for Spain in cycling in the 1992 Olympics": "Jose Manuel Moreno",
		"Who is the tallest basketball player in the world": "Manute Boll - 2.31m",
		"What do you use to take a cork out of a bottle": "a corkscrew",
		"What language has the most words": "English",
		"What\'s the name of the main airport in Madrid": "Barajas",
		"What money do they use in Japan": "yen",
		"What year did Paquirri die": "1984 or 1985",
		"Where does the American president live": "The White House",
		"What is the first letter on a typewriter": "Q",
		"What do the opposite sides of a dice add up to": "7",
		"Which fast food restaurants were established by Ray Kroc": "McDondalds",
		"How long is a round in boxing": "3 minutes",
		"Who is the Prime Minister of Britain": "John Major",
		"What\'s the highest score in a gymnastics exercise": "10",
		"What time do the pubs normally close in England": "11 o\'clock",
		"How many months have 31 days": "7",
		"How many eyes are there on a pack of 52 cards": "42",
		"What is the main language in Albania": "Tosco",
		"What\'s the fastest passenger plane in the world": "concorde",
		"What are the Sun, the \"Independent and the Guardian\"": "newspapers",
		"How many coloured balls are there in billiards": "15",
		"What\'s the longest word in Spanish": "superextraordinarissimo",
		"How many players are there in a basketball team": "5",
		"Which is the most spoken language": "Chinese",
		"How many lanes does an olympic swimming pool have": "8",
		"In what language does \"obrigado\" mean \"thank you\"": "Portuguese",
		"How many squares are there on a chess board": "64",
		"How many prongs are there on a fork": "4",
		"Who starts first in chess": "white",
		"How many events are there in the decathlon": "10",
		"What activity other than jumping are kangaroos good at": "boxing",
		"How many players are there in a volleyball team": "6",
		"What are the five colours of the Olympic rings": "r,y,g,blue black",
		"Where are the most expensive seats at a bullfight": "in the shade",
		"Who named a perfume for her fashion shows on the 5th day of the month": "Chanel",
		"How many dots are there on two dice": "42",
		"What horoscope sign has a crab": "cancer",
		"In which shop can you buy books in England": "bookshop",
		"Where does the British Prime Minister live": "10, Downing Street",
		"How long is the compulsory military service in England": "it doesn\'t exist",
		"What does the female praying mantis do after she\'s made love": "eats the male",
		"How many colours are there in a rainbow": "7",
		"How many legs has a spider got": "8",
		"What are the three primary colours": "red, blue and yellow",
		"What type of elephant has got the biggest ears": "African",
		"Who invented the electric light bulb": "Thomas Edison",
		"Who invented the telephone": "Bell",
		"Which nail grows fastest": "middle",
		"What temperature does water boil at": "100C",
		"Who discovered penicillin": "Fleming",
		"What did Joseph Priesley discover in 1774": "Oxygen",
		"Where is the smallest bone in the body": "ear",
		"Which is the only mammal that can\'t jump": "elephant",
		"What does the roman numeral C represent": "100",
		"What colour is a panda": "black and white",
		"What\'s the smallest type of tree in the world": "Bonsai",
		"Who invented television": "John Logie Baird",
		"Who said E=mc2": "Einstein",
		"Which planet is nearest the sun": "Mercury",
		"What colours make purple": "red and blue",
		"What\'s the hardest rock": "diamond",
		"How much does a litre of water weigh": "1kg"
	};
	
	for (var key in object) {
		questions.push({
			"question": key,
			"answer": object[key]
		});
	};
})();

var getNextQuestion = function() {
	if (this.count == undefined) {
		this.count = 0;
	} else {
		this.count = (this.count + 1) % questions.length;
	}
	
	return questions[this.count].question;
};

var getAnswer = function() {
	return questions[this.count].answer;
};

for (var i = 0; i < 80; i++) {
	console.log(getNextQuestion());
	console.log(getAnswer());
};